import { Navigation } from '@/components/Navigation';

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="space-y-4">
      <h2 className="font-heading text-2xl font-bold text-[var(--color-text-primary)] md:text-3xl">
        {title}
      </h2>
      <div className="space-y-4 font-body text-base leading-relaxed text-[var(--color-text-secondary)] md:text-lg">
        {children}
      </div>
    </section>
  );
}

export default function PrivacyPolicy() {
  return (
    <>
      <Navigation />
      <main className="px-6 pt-32 pb-24">
        <article className="mx-auto flex max-w-4xl flex-col gap-10 rounded-[2rem] border border-[var(--color-border)] bg-[var(--color-bg-surface)] p-8 shadow-xl backdrop-blur-xl md:p-12">
          <header className="border-b border-[var(--color-border)] pb-8">
            <p className="font-body text-xs font-semibold uppercase tracking-[0.28em] text-[var(--color-primary)]">
              Legal
            </p>
            <h1 className="mt-4 font-heading text-4xl font-bold text-[var(--color-text-primary)] md:text-5xl">
              Privacy Policy
            </h1>
            <p className="mt-4 font-subheading italic text-[var(--color-text-secondary)]">
              Last updated: February 16, 2026
            </p>
          </header>

          <div className="space-y-4 font-body text-base leading-relaxed text-[var(--color-text-secondary)] md:text-lg">
            <p>
              This Privacy Policy describes Our policies and procedures on the collection, use and
              disclosure of Your information when You use the Service and tells You about Your
              privacy rights and how the law protects You.
            </p>
            <p>
              We use Your Personal Data to provide and improve the Service. By using the Service,
              You agree to the collection and use of information in accordance with this Privacy
              Policy.
            </p>
          </div>

          <Section title="Interpretation and Definitions">
            <h3 className="font-heading text-xl font-bold text-[var(--color-text-primary)]">
              Interpretation
            </h3>
            <p>
              The words whose initial letters are capitalized have meanings defined under the
              following conditions. The following definitions shall have the same meaning regardless
              of whether they appear in singular or in plural.
            </p>
            <h3 className="pt-2 font-heading text-xl font-bold text-[var(--color-text-primary)]">
              Definitions
            </h3>
            <p>For the purposes of this Privacy Policy:</p>
            <ul className="list-disc space-y-2 pl-6">
              <li>
                <strong className="text-[var(--color-text-primary)]">Account</strong> means a
                unique account created for You to access our Service or parts of our Service.
              </li>
              <li>
                <strong className="text-[var(--color-text-primary)]">Application</strong> refers
                to COUNT, the software program provided by the Company.
              </li>
              <li>
                <strong className="text-[var(--color-text-primary)]">Company</strong> means COUNT.
              </li>
              <li>
                <strong className="text-[var(--color-text-primary)]">Country</strong> refers to
                Israel.
              </li>
              <li>
                <strong className="text-[var(--color-text-primary)]">Device</strong> means any
                device that can access the Service such as a computer, a cell phone or a digital
                tablet.
              </li>
              <li>
                <strong className="text-[var(--color-text-primary)]">Personal Data</strong> is any
                information that relates to an identified or identifiable individual.
              </li>
              <li>
                <strong className="text-[var(--color-text-primary)]">Service</strong> refers to the
                Application.
              </li>
              <li>
                <strong className="text-[var(--color-text-primary)]">Usage Data</strong> refers to
                data collected automatically, either generated by the use of the Service or from the
                Service infrastructure itself.
              </li>
              <li>
                <strong className="text-[var(--color-text-primary)]">You</strong> means the
                individual accessing or using the Service, or the company, or other legal entity on
                behalf of which such individual is accessing or using the Service.
              </li>
            </ul>
          </Section>

          <Section title="Collecting and Using Your Personal Data">
            <h3 className="font-heading text-xl font-bold text-[var(--color-text-primary)]">
              Types of Data Collected
            </h3>
            <h4 className="pt-2 font-heading text-lg font-bold text-[var(--color-text-primary)]">
              Personal Data
            </h4>
            <p>
              While using Our Service, We may ask You to provide Us with certain personally
              identifiable information that can be used to contact or identify You. This may include
              your email address, first name and last name, and usage data.
            </p>
            <h4 className="pt-2 font-heading text-lg font-bold text-[var(--color-text-primary)]">
              Usage Data
            </h4>
            <p>
              Usage Data is collected automatically when using the Service. It may include
              information such as Your device&apos;s IP address, browser type, browser version, the
              pages of our Service that You visit, the time and date of Your visit, the time spent
              on those pages, unique device identifiers, and other diagnostic data.
            </p>
            <h4 className="pt-2 font-heading text-lg font-bold text-[var(--color-text-primary)]">
              Information Collected While Using the Application
            </h4>
            <p>In order to provide features of Our Application, We may collect:</p>
            <ul className="list-disc space-y-2 pl-6">
              <li>
                <strong className="text-[var(--color-text-primary)]">
                  Personal Experience Data:
                </strong>{' '}
                details about personal experiences you record in your journal, including dates, notes,
                and personal reflections. This data is private and encrypted as part of our security model.
              </li>
              <li>
                <strong className="text-[var(--color-text-primary)]">Security Logs:</strong> events
                related to account security such as login attempts and biometrics status.
              </li>
            </ul>
            <p>
              This information is used solely to provide the core functionality of COUNT. The data
              is stored securely and is not shared with third parties for marketing purposes.
            </p>
          </Section>

          <Section title="Use of Your Personal Data">
            <p>The Company may use Personal Data for the following purposes:</p>
            <ul className="list-disc space-y-2 pl-6">
              <li>To provide and maintain our Service, including to monitor usage of the Service.</li>
              <li>To manage Your Account and registration as a user of the Service.</li>
              <li>
                To perform contractual obligations related to products, items, or services You have
                purchased.
              </li>
              <li>
                To contact You by email, phone, SMS, or other equivalent forms of electronic
                communication.
              </li>
              <li>
                To provide You with news, special offers, and general information about related
                goods, services, and events.
              </li>
              <li>To manage Your requests and support inquiries.</li>
            </ul>
          </Section>

          <Section title="Retention of Your Personal Data">
            <p>
              The Company will retain Your Personal Data only for as long as necessary for the
              purposes set out in this Privacy Policy, including compliance with legal obligations,
              resolving disputes, and enforcing legal agreements and policies.
            </p>
          </Section>

          <Section title="Data Sharing via the Community Feature (Opt-In)">
            <p>
              If You explicitly opt in to the COUNT community feature, You acknowledge and consent
              to the transmission of your selected journal entries to other approved users. When You
              share an entry through a view-once mechanism, the encrypted payload is stored only as
              long as needed for delivery and is deleted after viewing according to the feature
              design.
            </p>
            <p>
              We do not control what a recipient does once information is displayed on their device.
            </p>
          </Section>

          <Section title="Transfer of Your Personal Data">
            <p>
              Your information may be processed at the Company&apos;s operating offices and in other
              places where parties involved in the processing are located. This may include transfers
              to jurisdictions with different data protection laws.
            </p>
          </Section>

          <Section title="Delete Your Personal Data">
            <p>
              You have the right to delete or request assistance in deleting the Personal Data that
              We have collected about You. Our Service may allow You to delete certain information
              from within the app itself or through account settings.
            </p>
          </Section>

          <Section title="Disclosure and Security">
            <ul className="list-disc space-y-2 pl-6">
              <li>
                <strong className="text-[var(--color-text-primary)]">Business Transactions:</strong>{' '}
                If the Company is involved in a merger, acquisition, or asset sale, Personal Data
                may be transferred.
              </li>
              <li>
                <strong className="text-[var(--color-text-primary)]">Law Enforcement:</strong>{' '}
                Personal Data may be disclosed where required by law or valid legal process.
              </li>
            </ul>
            <p>
              While We use commercially reasonable means to protect Personal Data, no method of
              transmission over the Internet or electronic storage is completely secure.
            </p>
          </Section>

          <Section title="Children&#39;s Privacy and Other Websites">
            <p>
              Our Service does not address anyone under the age of 18. We do not knowingly collect
              personally identifiable information from anyone under 18.
            </p>
            <p>
              Our Service may contain links to third-party websites. We strongly advise You to
              review the privacy policy of every site You visit.
            </p>
          </Section>

          <Section title="Changes to this Privacy Policy">
            <p>
              We may update this Privacy Policy from time to time. Any changes will be posted on
              this page.
            </p>
          </Section>

          <Section title="Contact Us">
            <p>If you have any questions about this Privacy Policy, you can contact us:</p>
            <ul className="list-disc pl-6">
              <li>
                By email:{' '}
                <a
                  href="mailto:nevo.iflah6@icloud.com"
                  className="text-[var(--color-primary)] transition-colors hover:opacity-80"
                >
                  nevo.iflah6@icloud.com
                </a>
              </li>
            </ul>
          </Section>
        </article>
      </main>

      <footer className="border-t border-[var(--color-border)] bg-[var(--color-bg-default)] px-6 py-12">
        <div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-6 md:flex-row">
          <div className="flex flex-wrap justify-center gap-8 font-body text-sm text-[var(--color-text-secondary)]">
            <a href="/privacy-policy" className="text-[var(--color-primary)] transition-colors">
              Privacy Policy
            </a>
            <a href="/terms-of-service" className="transition-colors hover:text-[var(--color-primary)]">
              Terms of Service
            </a>
            <a
              href="mailto:support@countintimacyjournal.com"
              className="transition-colors hover:text-[var(--color-primary)]"
            >
              Support
            </a>
          </div>

          <div className="font-subheading text-sm text-[var(--color-text-secondary)]">
            &copy; {new Date().getFullYear()} COUNT. All rights reserved.
          </div>
        </div>
      </footer>
    </>
  );
}
